# Generated by Django 3.2.16 on 2022-11-19 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50)),
                ('Author', models.CharField(max_length=50)),
                ('Description', models.TextField(max_length=200)),
            ],
        ),
    ]
